# CPack configuration for RPLC executable package
set(CPACK_PACKAGE_NAME "rplc")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "RPLC - RPL Command Line Tool")

# Generators for executable (end-user tool)
set(CPACK_GENERATOR "TGZ;ZIP;DEB;RPM;NSIS")

# Debian settings for executable package
set(CPACK_DEBIAN_PACKAGE_NAME "rplc")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "")

# RPM settings for executable package
set(CPACK_RPM_PACKAGE_NAME "rplc")
set(CPACK_RPM_PACKAGE_LICENSE "ISC")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_PACKAGE_REQUIRES "")

# NSIS installer settings for Windows
set(CPACK_NSIS_DISPLAY_NAME "RPLC ${CPACK_PACKAGE_VERSION}")
set(CPACK_NSIS_PACKAGE_NAME "RPLC")
set(CPACK_NSIS_MODIFY_PATH ON)
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
